### ISSUE TITLE
object prototypes

### ISSUE THREAD

**Issue by rlieberman** [shiffman/Programming-from-A-to-Z-F15#12]
do you have any notes (and/or more examples) on object prototypes? livestream yesterday was super helpful but wondering if you can point me to any resources on prototypes specifically.

**Comment by rlieberman** [comment]
sorry, to be more specific: i'm clear about how to write a constructor function but confused about when to use the prototype property.

**Comment by shiffman** [comment]
This is a great question.  I do intend to have this discussion a bit in class.  Specifically, we'll need a deeper understanding of objects and prototypical inheritance for week 6 (where we'll build more complex data structures for text analysis.)  I have this [objects in js walk-through](https://github.com/shiffman/A2Z-F15/tree/gh-pages/week1/01_objects_in_JS_p5/00_JS_objects_walkthrough) which I need to comment and write up notes on.

I'll leave this open as a reminder to get to this.

For now, I might recommend this incredibly thorough video to prepare for this discussion.  It's more than we need for this course, but it goes through everything.  I watch this probably once a year.

http://www.objectplayground.com/

**Comment by shiffman** [comment]
This was covered in week 8, however, it needs some online notes to go along with the examples.   Covered now in #20.
